### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by acheshkov** [vincenthz/hs-crypto-cipher#1]
I can not instalI this package. i have ghc-7.0.1. 

anton@anton-laptop:~/projects/estate-web$ cabal install cryptocipher
Resolving dependencies...
Configuring cryptocipher-0.2...
Preprocessing library cryptocipher-0.2...
Preprocessing executables for cryptocipher-0.2...
Building cryptocipher-0.2...
[1 of 4] Compiling Number.ModArithmetic ( Number/ModArithmetic.hs, dist/build/Number/ModArithmetic.o )
[2 of 4] Compiling Crypto.Cipher.RSA ( Crypto/Cipher/RSA.hs, dist/build/Crypto/Cipher/RSA.o )

Crypto/Cipher/RSA.hs:92:51:
    Overlapping instances for Monad (Either Error)
      arising from a use of `>>='
    Matching instances:
      instance Monad (Either e) -- Defined in Control.Monad.Instances
      instance Monad (Either Error)
        -- Defined at Crypto/Cipher/RSA.hs:51:10-29
    In the expression: dp pk c >>= unpadPKCS1
    In an equation for`decrypt':
        decrypt pk c
          | B.length c /= (private_sz pk) = Left MessageSizeIncorrect
          | otherwise = dp pk c >>= unpadPKCS1
          where
              dp
                = if private_p pk /= 0 && private_q pk /= 0 then dpFast else dpSlow
cabal: Error: some packages failed to install:
cryptocipher-0.2 failed during the building phase. The exception was:
ExitFailure 1

**Comment by vincenthz** [comment]
odd. there's a specific #if MIN_VERSION at this location to prevent this exact same thing from happening. Can you check which base version do you have ? also can you check that commenting the instance class in the ifdef make it works.

**Comment by acheshkov** [comment]
I have base-4.3.0.0 package. 
"Comment" hack i will try later.

**Comment by acheshkov** [comment]
strange. in manual mode via runhaskell i installed without problems

**Comment by vincenthz** [comment]
I've fixed the issue. it was linked to the fact that the cabal macro doesn't wrap the boolean expression with () leading the ! to "enter" the expression. Thanks for reporting.

**Comment by acheshkov** [comment]
thanks you !!! ;)
