### ISSUE TITLE
AES should test for NI

### ISSUE THREAD

**Issue by TomMD** [vincenthz/hs-crypto-cipher#11]
I propose you move from naming the module AES.NI to AES.C and test for the NI instruction or fall back on non-NI instructions.

The intel-aes package (Ryan's package) includes bindings to a routine that tests for CPU support of the NI instruction.  This could be done at run-time and you could switch to gladman.  I know it sounds like just using intel-aes, but that's a bit messy these days and currently doesn't build on GHC 7.4.1 (or windows).

If this is acceptable, I might have time to move this forward myself.

**Comment by vincenthz** [comment]
I've created the cpu package for this purpose. Mainly my plan is to have a runtime constant that detect which implementation to use (NI, C, or haskell) using the Arch and cpuid when arch is x86|x86_64. Any contribution to hook the whole system up is more than welcome though.

**Comment by TomMD** [comment]
Great, I'll try to move things forward.
