### ISSUE TITLE
Index out of bounds problems

### ISSUE THREAD

**Issue by carlssonia** [vincenthz/hs-crypto-cipher#15]
The following program crashes with a segmentation fault, which I suspect is due to an index out of bound in `Crypto.Cipher.AES.swapBlock`:

```
import qualified Data.ByteString as BS
import qualified Crypto.Cipher.AES as AES
main :: IO ()
main = print $ AES.decryptCBC (either undefined id $ AES.initKey256 (BS.replicate 32 0))
                              (BS.replicate 16 0)
                              BS.empty
```

Tested against cryptocipher-0.3.2.

**Comment by vincenthz** [comment]
thanks for the report; core{decrypt,Encrypt} is never meant to be called without valid data, and the bug was in the chunking function.

**Comment by carlssonia** [comment]
Thanks, @vincenthz !
