### ISSUE TITLE
Camellia test fails on PowerPC

### ISSUE THREAD

**Issue by erikd** [vincenthz/hs-crypto-cipher#18]
Even after @nometa's patch fac02f7fff8, the Camellia tests still fail:

  Camellia: [Failed]
    Falsifiable with seed -1686443647, after 1 tests.
   Reason: Exception: 'expected:  [61,2,128,37,177,86,50,124,23,247,98,193,242,203,202,113]
                                        got: [196,109,115,240,38,60,239,236,92,77,88,226,233,80,77,51]'

Working on a fix.

**Comment by erikd** [comment]
This is actually a GHC optimiser bug that seems to only affect PowerPC.

GHC bug report here: http://hackage.haskell.org/trac/ghc/ticket/6156

Closing this bug.

**Comment by vincenthz** [comment]
darn that's quite obscure !

However i wouldn't worry too much about camellia; i don't believe there's one actual user of it on x86/64, let alone on powerpc (or every other unsupported haskell architectures)

**Comment by erikd** [comment]
Well there are a whole bunch of architectures that GHC Central considers un-supported but that Debain needs to support. Debian policy suggests that wherever possible, if a package is available for x86/x86-64 then it should be available for all other architectures that Debian supports (which includes PowerPC, MIPS, ARM and some others).

The Debian maintainers currently patch both GHC and a large number of libraries to support these other architectures and feed the patches back upstream.

**Comment by vincenthz** [comment]
@erikd: i'm aware of Debian policy, but i think camellia as it stands, is just a piece of example/preview code.
