### ISSUE TITLE
Test suite doesn't compile

### ISSUE THREAD

**Issue by peti** [vincenthz/hs-crypto-cipher#29]
The problem seems to be that the test suite depends on crypto-cipher-tests, but doesn't declare that dependency. A complete build is:

  Configuring crypto-cipher-types-0.0.1...
  Warning: 'hs-source-dirs: ../tests' is a relative path outside of the source
  tree. This will not work when generating a tarball with 'sdist'.
  Warning: 'hs-source-dirs: ../tests' directory does not exist.
  Dependency HUnit -any: using HUnit-1.2.5.2
  Dependency QuickCheck >=2: using QuickCheck-2.6
  Dependency base ==4.*: using base-4.6.0.1
  Dependency byteable >=0.1.1: using byteable-0.1.1
  Dependency bytestring -any: using bytestring-0.10.0.2
  Dependency crypto-cipher-types -any: using crypto-cipher-types-0.0.1
  Dependency mtl -any: using mtl-2.1.2
  Dependency securemem >=0.1.1: using securemem-0.1.2
  Dependency test-framework -any: using test-framework-0.8
  Dependency test-framework-hunit -any: using test-framework-hunit-0.3.0
  Dependency test-framework-quickcheck2 -any: using
  test-framework-quickcheck2-0.3.0.1
  Using Cabal-1.16.0 compiled by ghc-7.6
  Using compiler: ghc-7.6.3
  Using install prefix:
  /nix/store/nh0s04ir78r7n1aa3vyavv4pips5ifzr-haskell-crypto-cipher-types-ghc7.6.3-0.0.1
  Binaries installed in:
  /nix/store/nh0s04ir78r7n1aa3vyavv4pips5ifzr-haskell-crypto-cipher-types-ghc7.6.3-0.0.1/bin
  Libraries installed in:
  /nix/store/nh0s04ir78r7n1aa3vyavv4pips5ifzr-haskell-crypto-cipher-types-ghc7.6.3-0.0.1/lib/crypto-cipher-types-0.0.1/ghc-7.6.3
  Private binaries installed in:
  /nix/store/nh0s04ir78r7n1aa3vyavv4pips5ifzr-haskell-crypto-cipher-types-ghc7.6.3-0.0.1/libexec
  Data files installed in:
  /nix/store/nh0s04ir78r7n1aa3vyavv4pips5ifzr-haskell-crypto-cipher-types-ghc7.6.3-0.0.1/share/crypto-cipher-types-0.0.1
  Documentation installed in:
  /nix/store/nh0s04ir78r7n1aa3vyavv4pips5ifzr-haskell-crypto-cipher-types-ghc7.6.3-0.0.1/share/doc/crypto-cipher-types-0.0.1
  No alex found
  Using ar found on system at:
  /nix/store/46595bx2k3yjznihv898592qnzirbvgm-binutils-2.23.1/bin/ar
  No c2hs found
  No cpphs found
  No ffihugs found
  Using gcc version 4.6.3 found on system at:
  /nix/store/imgyva7wqc81w91q1agfrqk77b827hqv-gcc-wrapper-4.6.3/bin/gcc
  Using ghc version 7.6.3 found on system at:
  /nix/store/5brgfcsds7la03yy2l8g3jwjyasmalqj-ghc-7.6.3-wrapper/bin/ghc
  Using ghc-pkg version 7.6.3 found on system at:
  /nix/store/5brgfcsds7la03yy2l8g3jwjyasmalqj-ghc-7.6.3-wrapper/bin/ghc-pkg
  No greencard found
  Using haddock version 2.13.2 found on system at:
  /nix/store/xq36g6s6gy2ww14pqaspvm6ma98n6dc3-ghc-7.6.3/bin/haddock
  No happy found
  No hmake found
  Using hpc version 0.6 found on system at:
  /nix/store/5brgfcsds7la03yy2l8g3jwjyasmalqj-ghc-7.6.3-wrapper/bin/hpc
  Using hsc2hs version 0.67 found on system at:
  /nix/store/5brgfcsds7la03yy2l8g3jwjyasmalqj-ghc-7.6.3-wrapper/bin/hsc2hs
  No hscolour found
  No hugs found
  No jhc found
  Using ld found on system at:
  /nix/store/imgyva7wqc81w91q1agfrqk77b827hqv-gcc-wrapper-4.6.3/bin/ld
  No lhc found
  No lhc-pkg found
  No nhc98 found
  No pkg-config found
  Using ranlib found on system at:
  /nix/store/46595bx2k3yjznihv898592qnzirbvgm-binutils-2.23.1/bin/ranlib
  Using strip found on system at:
  /nix/store/46595bx2k3yjznihv898592qnzirbvgm-binutils-2.23.1/bin/strip
  Using tar found on system at:
  /nix/store/db7c4cg09100f927jw73qrg5nnvqpvc9-gnutar-1.26/bin/tar
  No uhc found
  building
  Building crypto-cipher-types-0.0.1...
  Preprocessing library crypto-cipher-types-0.0.1...
  [1 of 2] Compiling Crypto.Cipher.Types.GF ( Crypto/Cipher/Types/GF.hs, dist/build/Crypto/Cipher/Types/GF.o )
  [2 of 2] Compiling Crypto.Cipher.Types ( Crypto/Cipher/Types.hs, dist/build/Crypto/Cipher/Types.o )
  In-place registering crypto-cipher-types-0.0.1...
  Preprocessing test suite 'test-crypto-cipher-types' for
  crypto-cipher-types-0.0.1...

  tests/Tests.hs:6:8:
      Could not find module `Crypto.Cipher.Tests'
      Perhaps you meant
        Crypto.Cipher.Types (from crypto-cipher-types-0.0.1)
      Use -v to see a list of the files searched for.

**Comment by vincenthz** [comment]
Thanks. i fixed this. i fixed the chicken&egg problem with the tests by moving the test suite in the crypto-cipher-tests package, so it should work on hackage too, not just in the repository as before.
