### ISSUE TITLE
Crypto.Cipher.Types classes and other ideas

### ISSUE THREAD

**Issue by stbuehler** [vincenthz/hs-crypto-cipher#40]
Hi,
- I think `aeadInit` shouldn't take the IV; especially GCM does a lot of initial work with the key (expensive), but changing the IV/nonce is easy. So maybe add a second step to setup the IV in the AEADModeImpl class.
- I'm not sure what the standard "error handling" way is, but sometimes I feel having a Monad to `fail` in could be useful
- I thought about your `raw interface` idea (with `Ptr Word8 -> ...`): If i wanted a C interface, I'd be coding C. So please don't use `Ptr Word8` - perhaps there is a safe way to pass modifyable Buffers (Data.Vector.Storable.Mutable ?) in the IO/ST monad.
- I pushed https://github.com/stbuehler/haskell-nettle (docs at http://stbuehler.github.io/haskell-nettle/). I'll try to add some checks (n*blockSize arguments and so on), so that it should be "safe" to use, and add the hash methods too.
- I think you have some test vectors for the ciphers you implemented; it would be nice if you could export them in `crypto-cipher-tests` so others could reuse them (perhaps selecting them based on the name of the cipher, as type obviously can't work). It'd be also nice to check two different implementations of the same cipher against each other (instead of only checking whether a cipher can decrypt its own encrypted stuff).

**Comment by vincenthz** [comment]
- that's a good idea for aeadInit and the IV/nonce splitting.
- I don't understand your question about the standard error handling
- the raw interface is useful: it's not about taking the pure interface away, it's about scaling internally and provide mean to do it externally too; there's lots of things (bytestring, vector, ..) where having access to the internal to present a feature that is pure overall is useful. My guess is that for example the pure CBC function can be written much better in term of mutable ECB function than in term of concat . encryptECB . chunk . The second things is that, in some case, programming low level is useful even in haskell. For an example in a tight loop or something where performance matters, you might want a mutable context and updates. this is certainly true for e.g. vector where you can have a freeze/thaw operations to do necessary stuff.
- i'm not sure pushing the KATs into tests is the best things to do. It would have certain nice advantages though.

**Comment by vincenthz** [comment]
also i've pushed to the mutable branch in this repository. you can see the extents of the changes so far.

**Comment by stbuehler** [comment]
- Error handling: for example, if the IV/nonce is splitted in AEAD, using a nonce with wrong length is an error (GCM/CCM need 12-byte nonces for example). Do you use a `Maybe` return type, or just call `error`? I sometimes now went for generic Monads in that case; it can be used like Maybe, but I also can easily use it in other monadic context, and get a nice error message if it fails, instead of just `Nothing`. As I said I'm not sure what the "right" thing is.
- The block cipher modes are a bad example - the default implementation may be slow, but you always can implement a faster one when you know the internals - that is why they are part of the class, right?. I'm not convinced you need more performance outside of this stuff.
  
  But I think it should be possible to combine both; all you need is the combination of a pointer, a size, and the assertion that they mark a valid mutable area. "Freezing" them into ByteStrings might require locking if you want to do it without copying; creating them from ByteStrings -- well I guess you can't check whether it is the only reference, so you'll have to copy the data.

JFYI: http://hackage.haskell.org/package/nettle-0.1.0 is on hackage now.

**Comment by vincenthz** [comment]
- at the moment the error handling is a bit ad-hoc. Not sure what's the right thing to do either here: i'm trying to get away from partial function and error at the moment (not necessarily everything, but stuff that make more sense)
- GCM allows for arbitrary sized Nonce, with 12 bytes being the recommended value.
- Yes, it's why they are part of the class, i.e. overriding for speed. However when it's left as default, it's really slow, which is the reason behind exposing a mutating version: it should be easier to write a much faster version which is generic provided a mutable version of encrypt/decrypt blocks.
