### ISSUE TITLE
Support fast sign/decrypt with pinv ("u")

### ISSUE THREAD

**Issue by singpolyma** [vincenthz/hs-crypto-cipher#6]
I'm working with OpenPGP keys and trying to do signing using this library.  The "slow" n, d version works fine, but I cannot do "fast" because I do not have qinv (`inverse q p`) but instead have what http://tools.ietf.org/html/rfc4880#section-5.5.3 calls "u", `inverse p q`.

I've played with getting this working myself, but my RSA is a bit rusty.

**Comment by vincenthz** [comment]
I think you can just swap p and q related fields (p,q,dP,dQ) in the priv structure and your pinv just become qinv.

**Comment by singpolyma** [comment]
Thanks!  That worked.
