### ISSUE TITLE
RSA "slow sign" is really slow

### ISSUE THREAD

**Issue by singpolyma** [vincenthz/hs-crypto-cipher#7]
I was just doing some benchmark comparisons against http://hackage.haskell.org/package/Crypto.  Crypto's RSA support is just (n,d) and examining the code shows exactly the same high-level strategy as cryptocipher uses in the "slow" (n,d) case.  However, Crypto is markedly faster than cryptocipher in this case.  It may be worth looking at the implementation in that package and identifying what makes cryptocipher slower.

**Comment by singpolyma** [comment]
On investigation, replacing the `exponantiation_rtl_binary` in cryptocipher with the following from Crypto makes it get **way** faster:

```
expmod :: Integer -> Integer -> Integer -> Integer
expmod a x m |  x == 0    = 1
             |  x == 1    = a `mod` m
             |  even x    = let p = (expmod a (x `div` 2) m) `mod` m
                            in  (p^2) `mod` m
             |  otherwise = (a * expmod a (x-1) m) `mod` m
```

**Comment by vincenthz** [comment]
Thanks. i agree this is slower than it should be, and i had a look but was distracted in rewriting a integer library :-) The algorithm itself is bound to be fast, but for some reason there's some operations (shiftR on Integer maybe) that in haskell result in braindead performance. In a meantime, I'll replace the implementation thanks
