### ISSUE TITLE
Crypto.Classes, hashes, and cryptocipher

### ISSUE THREAD

**Issue by singpolyma** [vincenthz/hs-crypto-cipher#8]
I'm looking at writing Crypto.Classes instances for some of the things in cryptocipher.

`Crypto.Cipher.RSA.sign` has type `HashF -> HashASN1 -> PrivateKey -> ByteString -> Either Error ByteString`
`Crypto.Classes.Signing.sign` has type `CryptoRandomGen g => g -> v -> ByteString -> Either GenError (ByteString, g)`

For RSA signing we don't need the random number generator, so we con just return it directly.  No problem.  Mapping Error onto GenError is also possible.

The real issue is that `Crypto.Cipher.RSA.sign` does the padding and hashing **and** the signing.  There is in fact no exported way to create the raw ByteString to be signed.

This is additionally a problem in my OpenPGP implementation because OpenPGP requires a piece of the raw, unsigned hash output to be stored.

I propose adding a `sign'` or `sign_` to `Crypto.Cipher.RSA` (and other asymmetric modules) that takes just a private key and bytestring, and exporting `makeSignature`.

If this seems like an acceptable solution to you, I will start looking at coding it up.

**Comment by vincenthz** [comment]
Which part of the raw bytestring does openpgp need ?

If it end up exported, it's probably sensible to rename makeSignature to paddingSchemeForSignature or such name.

**Comment by singpolyma** [comment]
Actually, at the moment, I've become unsure which bit OpenPGP needs.  Even gpg seems to not care what I give it for that particular field.

The Crypto-API classes still need this, though.

And, sure, could also rename it pkcs1_5_pad or something

**Comment by vincenthz** [comment]
this has been fixed in crypto-pubkey. Crypto.PubKey.RSA.PKCS15.pad
