### ISSUE TITLE
Missing 'cpu' dependency

### ISSUE THREAD

**Issue by btubbs** [vincenthz/hs-crypto-cipher#9]
brent.tubbs hedy ~ $ cabal install cryptocipher
Resolving dependencies...
cabal: cannot configure cryptocipher-0.3.1. It requires cpu ==0.1.*
There is no available version of cpu that satisfies ==0.1.*

**Comment by vincenthz** [comment]
apologies ! forgot to upload cpu to hackage. now resolved.
